# @author Vivian Tsai
# Grammar (PO-POS)

# Full sentence rules.
1	ROOT	S .

# Basic grammar rules.
1	S	It was AP
1	S	I thought it was AP
1	S	I thought it was PosP
1	S	I really Verb it 
1	AP	Int Adj
1	AP	Adj

# Vocabulary.
1	PosP	definitely worth watching
1	PosP	a great time
1	PosP	Int impressive
1	PosP	fairly well done

1	Verb	enjoyed
1	Verb	liked

1	Noun	friend
1	Noun	programmers

1	PP	in theaters
1	PP	at home
1	PP	at the Waterfront
1	PP	at the movie theater

1	Int	very
1	Int	really
1	Int	extremely

1	Adj	interesting
1	Adj	good
1	Adj	enjoyable	
